# Generated by Django 5.2.1 on 2025-05-27 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0003_alter_viaje_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='actividad',
            name='completada',
            field=models.BooleanField(default=False),
        ),
    ]
